version: '3'

services:  
  api:
    # image: api
    build: ./
    ports:
      - 5000:5000
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    environment:
      - DB_HOST=db
    # run tests instead of launching api
    command: npm test ./tests --watch
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: supersecret
